site_name: "continuiti"
site_dir: "docs_build"
site_url: "https://aai-institute.github.io/continuiti/"
repo_name: "aai-institute/continuiti"
repo_url: "https://github.com/aai-institute/continuiti"
copyright: "Copyright &copy; appliedAI Institute for Europe gGmbH"
remote_branch: gh-pages

watch:
  - src/continuiti

hooks:
  - build_scripts/copy_benchmarks.py

plugins:
  - autorefs
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: true
      caption_position: bottom
  - macros
  - mike:
      canonical_version: latest
  - search
  - section-index
  - alias:
      verbose: true
  - gen-files:
      scripts:
        - build_scripts/generate_api_docs.py
  - literate-nav:
      nav_file: SUMMARY.md
      implicit_index: false
      tab_length: 2
  - mknotebooks:
      execute: false
      enable_default_jupyter_cell_styling: false
      tag_remove_configs:
        remove_cell_tags:
          - hide
        remove_input_tags:
          - hide-input
        remove_all_outputs_tags:
          - hide-output
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
            - https://scikit-learn.org/stable/objects.inv
            - https://pytorch.org/docs/stable/objects.inv
          paths: [src]
          options:
            docstring_style: google
            docstring_section_style: spacy
            line_length: 80
            show_bases: true
            members_order: source
            show_submodules: false
            show_signature_annotations: false
            signature_crossrefs: true
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date
      fallback_to_build_date: true

theme:
  name: material
  custom_dir: docs/overrides
  logo: img/icon.png
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow
  palette: # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - css/extra.css
  - css/neoteroi.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  transferlab:
    website: https://transferlab.ai
  copyright_link: https://appliedai-institute.de
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aai-institute/continuiti
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/continuiti/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/appliedAI_gGmbH
    - icon: fontawesome/brands/linkedin
      link: https://de.linkedin.com/company/appliedai-institute-for-europe-ggmbh

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - markdown_captions
  - md_in_html
  - neoteroi.cards
  - codehilite
  - toc:
      permalink: True
      toc_depth: 3
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - docs_includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Home: index.md
  - Tutorials:
      - First Steps: tutorials/firststeps.md
      - Operators: tutorials/operators.md
      - Functions: tutorials/functions.ipynb
      - Training: tutorials/training.ipynb
      - FNO: tutorials/fno.ipynb
  - How-to Guides:
      - Time Series: how-to-guides/timeseries.ipynb
      - Super-resolution: how-to-guides/superresolution.ipynb
      - Physics-informed: how-to-guides/physicsinformed.ipynb
      - Meshes: how-to-guides/meshes.ipynb
      - Self-supervised: how-to-guides/selfsupervised.ipynb
  - Background:
      - Architectures: background/architectures.md
  - Reference:
      - API: api/continuiti/
      - Changelog: CHANGELOG.md
      - Contributing: CONTRIBUTING.md
  - Benchmarks: benchmarks/index.md
