defaults:
  - _self_
  - trainer: default

tol: 1e-2

hydra:
  mode: "MULTIRUN"

  sweeper:
    params:
      +seed: range(0, 10)
      +benchmark: sine
      +operator: deeponet_small, deeponet_large, belnet_small, neuraloperator
